/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef exp_CONSTANTS_H
#define exp_CONSTANTS_H

#include "exp_types.h"

namespace thrift { namespace example {

class expConstants {
 public:
  expConstants();

  int32_t MAX_RESULTS;
};

extern const expConstants g_exp_constants;

}} // namespace

#endif
