/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "exp_constants.h"

namespace thrift { namespace example {

const expConstants g_exp_constants;

expConstants::expConstants() {
  MAX_RESULTS = 100;

}

}} // namespace

